#' createDB
#'
#' @description
#' Produce a dataset containing relational data between HGNC symbols,
#' PDB IDs, PDB chain IDs, HGNC Transcript Names and HGNC Transcript IDs.
#' Refer to the data model to understand the structure
#' of the reference data base.
#'
#' @param geneList A dataframe generated by the biomaRt ensembl package
#' containing the data
#'
#' @return A dataset containing the relational data
#'
#' @export

createDB <- function(geneList) {

  myDB <- list()
  myDB <- addHGNC(myDB, geneList)
  myDB <- addTranscripts(myDB, geneList)
  myDB <- addpdbChain(myDB, geneList)
  myDB <- addPDB(myDB, geneList)

  return(myDB)
}

# [END]
